### ISSUE TITLE
Option to make the returned MongoClient tz_aware

### ISSUE THREAD

**Issue by languitar** [ClearcodeHQ/pytest-mongo#158]
`MongoClient` instances can optionally be timezone aware by providing the `tz_aware` parameter at construction time. It would be nice at least this parameter could be set such that the `mongodb` fixture returns clients with this (or other options) enabled. In my case, my application that I am testing requires timezone-aware clients and thus I cannot use the fixture right now.

**Comment by fizyk** [comment]
I'll welcome any contribution for this feature. Is there also a server setting for that, or only a client setting? Could you post a link to the client's/mongo docs?

**Comment by languitar** [comment]
It's a constructor argument to `MongoClient`: http://api.mongodb.com/python/current/api/pymongo/mongo_client.html. This is just a client-side setting regarding the way how datetime instances are created.
