### ISSUE TITLE
Mongodb noprocess factory

### ISSUE THREAD

**Issue by Cediddi** [ClearcodeHQ/pytest-mongo#256]
I maintain few postgresql and mongodb related applications and due to a testing requirement change I switched all my postgresql tests to utilize either postgresql_proc or postgresql_noproc depending on a cli parameter. I just found out pytest-mongo does not have a noproc factory.

I think, pytest-mongo features should be on par and in sync with pytest-postgresql.

**Comment by fizyk** [comment]
@Cediddi I'd welcome any pull requests duplicating that functionality. 

I don't have that much time to duplicate functionalityes across our databas related pytest plugins. So I actually implemented that where I had original requests. If you can commit a bit of time, please feel free to create a pull request.

**Comment by Cediddi** [comment]
I'd love to help, currently I'm a bit busy with other parts of our tests but mean time I'll raise this as an internal issue.

**Comment by fizyk** [comment]
please check version 2.1.0
