### ISSUE TITLE
How to load predefined data?

### ISSUE THREAD

**Issue by lfoppiano** [ClearcodeHQ/pytest-mongo#330]
Hi all, 
    I would like to load predefined data in the mongodb, before the tests. 
Something like it's explained in this other library for example 
https://github.com/mdomke/pytest-mongodb#configuration 

I did not find much in the documentation (the readme file in the root of this project). 

Thank you in advance :-)

**Comment by fizyk** [comment]
@lfoppiano there's no such functionality, you could, however, make a data fixture depending on the client fixture, fill in the MongoDB database in there, and use the given data fixture as a test dependency.

I do not have much time to work on that, not to mention that I haven't touched MongoDB in a long time. 
However, if you'd like to work on it, I'd welcome contributions with such functionality.

**Comment by lfoppiano** [comment]
Dear @fizyk. 
Thanks. No problem. 
I figure out that https://github.com/mdomke/pytest-mongodb still works although it has not been updated since several years.
