### ISSUE TITLE
Redundant requirement of redis  

### ISSUE THREAD

**Issue by tyzhnenko** [ClearcodeHQ/pytest-mongo#378]
## Issue
The package has redundant [dependency](https://github.com/ClearcodeHQ/pytest-mongo/blob/1318738f0e7ea00bf4bf0da3d906d9bde373a804/setup.cfg#L41) from redis package 

## Possible solution
Remove dependency due to no code using Redis

**Comment by fizyk** [comment]
Fixed with #413
